import type { Metadata } from 'next';
import './globals.css';
import { Montserrat, Playfair_Display, Parisienne } from 'next/font/google';
import Navbar from '@/shared/components/nav/Navbar';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
});

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display'
});

const parisienne = Parisienne({
  subsets: ['latin'],
  variable: '--font-parisienne',
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Nicole Augustaitis',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${montserrat.variable} ${playfairDisplay.variable} ${parisienne.variable}`}
    >
      <body>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
